// Every word on screen. Facts come from the client's previous video board (see brief.md).
export const COPY = {
  hook: ['TON SON', 'MÉRITE UN', ['VRAI ', 'STUDIO.']],
  brand: 'RZED',
  brandSub: 'RECORDS',
  studioLabel: "STUDIO D'ENREGISTREMENT",
  city: 'Livry-Gargan (93)',
  hours: 'Ouvert 7j/7 · 24h/24',
  tagline: 'La qualité pro accessible à tous',
  servicesTitle: ['TOUT POUR', 'TON SON'],
  services: [
    { key: 'rec', label: 'Enregistrement', img: 'singer' },
    { key: 'mix', label: 'Mixage', img: 'console' },
    { key: 'master', label: 'Mastering', img: 'monitors' },
    { key: 'beat', label: 'Beatmaking', img: 'pads' },
  ],
  chatTitle: 'ÉCRIS-NOUS.',
  chatName: 'RZED Records',
  chatStatus: 'en ligne',
  chat: [
    { me: true, text: 'Wesh 👋 t’as une dispo samedi pour enregistrer ?' },
    { me: false, text: 'Oui ! Samedi 17h–19h c’est libre ✅' },
    { me: true, text: 'C’est combien les 2h ?' },
    { me: false, text: '70€ la session de 2h 🔥' },
    { me: true, text: 'Je bloque ! 🔒' },
  ],
  chatChannels: 'WhatsApp · Appel · DM',
  tarifsTitle: ['NOS ', 'TARIFS'],
  tarifs: [
    { label: '1H DE SESSION', price: 35 },
    { label: '2H DE SESSION', price: 70 },
    { label: '3H DE SESSION', price: 100 },
  ],
  packsTitle: ['NOS ', 'PACKS'],
  packs: [
    { label: 'PACK 10H', price: 300 },
    { label: 'PACK 20H', price: 580 },
    { label: 'PACK 30H', price: 850 },
  ],
  packCta: 'Réserve en DM ou au 07 69 69 36 56',
  endTitle: ['RÉSERVE', 'TA SESSION'],
  phone: '07 69 69 36 56',
  phoneSub: 'WhatsApp · Appel · DM — 7j/7 · 24h/24',
  handle: '@rzed_records',
  handleSub: 'TikTok · Insta · Snap',
  mail: 'rzedrecords@gmail.com',
  address: '93190 Livry-Gargan',
};
